/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author João Augusto
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuCadHospedes = new javax.swing.JMenuItem();
        menuConHospedes = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuCadQuartos = new javax.swing.JMenuItem();
        menuConQuartos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuCadFuncionarios = new javax.swing.JMenuItem();
        menuConFuncionarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuConFornecedores = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        menuCadReserva = new javax.swing.JMenuItem();
        menuConReserva = new javax.swing.JMenuItem();
        menuFinalizarReserva = new javax.swing.JMenuItem();
        menuConsumo = new javax.swing.JMenu();
        menuConsumoConCliente = new javax.swing.JMenuItem();
        menuConsumoCadProd = new javax.swing.JMenuItem();
        menuConsumoServiços = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuFinConPagCad = new javax.swing.JMenuItem();
        menuFinConPagCon = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuFinConRecCad = new javax.swing.JMenuItem();
        menuFinConRecCon = new javax.swing.JMenuItem();
        menuFinanceiroBalanço = new javax.swing.JMenuItem();
        menuRelatórios = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuRelFinContasPagar = new javax.swing.JMenuItem();
        menuRelFinContasReceber = new javax.swing.JMenuItem();
        menuRelFinBalanço = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuRelResQuartosDisponiveis = new javax.swing.JMenuItem();
        menuRelResQuartosOcupados = new javax.swing.JMenuItem();
        menuRelResReservasFuturas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuRelHospedes = new javax.swing.JMenuItem();
        menuRelFuncionarios = new javax.swing.JMenuItem();
        menuRelFornecedores = new javax.swing.JMenuItem();
        menuSegurança = new javax.swing.JMenu();
        menuSegFazerBackup = new javax.swing.JMenuItem();
        menuSegRestaurarBackup = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        menuFerTelaFundoAdicionar = new javax.swing.JMenuItem();
        menuFerTelaFundoRemover = new javax.swing.JMenuItem();
        menuFerTelaFundoRestaurarPadrao = new javax.swing.JMenuItem();
        menuFerSobreSistema = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pro Hotel - Tela Principal");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pro Hotel - Sistema para gerenciamento de Hotéis - Desenvolvido por João Augusto - Todos os direitos reservados 2024 ©");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Pro   Hotel");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/905462.png"))); // NOI18N

        jLabel5.setText("Horário atual:");

        jLabel6.setText("Usuário:");

        jLabel7.setText("Cargo:");

        jLabel8.setText("Grau de acesso:");

        jLabel9.setText("nome");

        jLabel10.setText("texto");

        jLabel11.setText("texto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastros_resized.png"))); // NOI18N
        menuCadastros.setText("Cadastros   |");
        menuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu9.setText("Hospedes");

        menuCadHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuCadHospedes.setText("Cadastrar");
        menuCadHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospedesActionPerformed(evt);
            }
        });
        jMenu9.add(menuCadHospedes);

        menuConHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConHospedes.setText("Consultar");
        jMenu9.add(menuConHospedes);

        menuCadastros.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu10.setText("Quartos");

        menuCadQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuCadQuartos.setText("Cadastrar");
        menuCadQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadQuartosActionPerformed(evt);
            }
        });
        jMenu10.add(menuCadQuartos);

        menuConQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConQuartos.setText("Consultar");
        jMenu10.add(menuConQuartos);

        menuCadastros.add(jMenu10);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu1.setText("Funcionários");

        menuCadFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuCadFuncionarios.setText("Cadastrar");
        jMenu1.add(menuCadFuncionarios);

        menuConFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConFuncionarios.setText("Consultar");
        jMenu1.add(menuConFuncionarios);

        menuCadastros.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu2.setText("Fornecedores");

        menuCadFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuCadFornecedores.setText("Cadastrar");
        jMenu2.add(menuCadFornecedores);

        menuConFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConFornecedores.setText("Consultar");
        jMenu2.add(menuConFornecedores);

        menuCadastros.add(jMenu2);

        jMenuBar1.add(menuCadastros);

        menuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas_resized (1).png"))); // NOI18N
        menuReservas.setText("Reservas   |");
        menuReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuCadReserva.setText("Cadastrar Reserva");
        menuReservas.add(menuCadReserva);

        menuConReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConReserva.setText("Consultar Reserva");
        menuReservas.add(menuConReserva);

        menuFinalizarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFinalizarReserva.setText("Finalizar Reserva");
        menuReservas.add(menuFinalizarReserva);

        jMenuBar1.add(menuReservas);

        menuConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo_resized.png"))); // NOI18N
        menuConsumo.setText("Consumo   |");
        menuConsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuConsumoConCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConsumoConCliente.setText("Consumo Cliente");
        menuConsumo.add(menuConsumoConCliente);

        menuConsumoCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConsumoCadProd.setText("Produtos");
        menuConsumo.add(menuConsumoCadProd);

        menuConsumoServiços.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuConsumoServiços.setText("Serviços");
        menuConsumo.add(menuConsumoServiços);

        jMenuBar1.add(menuConsumo);

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro_resized.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro   |");
        menuFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu3.setText("Contas a Pagar");

        menuFinConPagCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFinConPagCad.setText("Cadastrar");
        jMenu3.add(menuFinConPagCad);

        menuFinConPagCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFinConPagCon.setText("Consultar");
        jMenu3.add(menuFinConPagCon);

        menuFinanceiro.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu4.setText("Contas a Receber");

        menuFinConRecCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFinConRecCad.setText("Cadastrar");
        jMenu4.add(menuFinConRecCad);

        menuFinConRecCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFinConRecCon.setText("Consultar");
        jMenu4.add(menuFinConRecCon);

        menuFinanceiro.add(jMenu4);

        menuFinanceiroBalanço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFinanceiroBalanço.setText("Balanço Empresarial");
        menuFinanceiro.add(menuFinanceiroBalanço);

        jMenuBar1.add(menuFinanceiro);

        menuRelatórios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios_resized.png"))); // NOI18N
        menuRelatórios.setText("Relatórios   |");
        menuRelatórios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu5.setText("Financeiro");

        menuRelFinContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelFinContasPagar.setText("Contas a Pagar");
        jMenu5.add(menuRelFinContasPagar);

        menuRelFinContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelFinContasReceber.setText("Contas a Receber");
        jMenu5.add(menuRelFinContasReceber);

        menuRelFinBalanço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelFinBalanço.setText("Balanço");
        jMenu5.add(menuRelFinBalanço);

        menuRelatórios.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu6.setText("Reservas");

        menuRelResQuartosDisponiveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelResQuartosDisponiveis.setText("Quartos Disponíveis");
        menuRelResQuartosDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelResQuartosDisponiveisActionPerformed(evt);
            }
        });
        jMenu6.add(menuRelResQuartosDisponiveis);

        menuRelResQuartosOcupados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelResQuartosOcupados.setText("Quartos Ocupados");
        jMenu6.add(menuRelResQuartosOcupados);

        menuRelResReservasFuturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelResReservasFuturas.setText("Reservas Futuras");
        jMenu6.add(menuRelResReservasFuturas);

        menuRelatórios.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu7.setText("Vendas");
        menuRelatórios.add(jMenu7);

        menuRelHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelHospedes.setText("Hospedes");
        menuRelatórios.add(menuRelHospedes);

        menuRelFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelFuncionarios.setText("Funcionários");
        menuRelatórios.add(menuRelFuncionarios);

        menuRelFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuRelFornecedores.setText("Fornecedores");
        menuRelatórios.add(menuRelFornecedores);

        jMenuBar1.add(menuRelatórios);

        menuSegurança.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/segurança_resized.png"))); // NOI18N
        menuSegurança.setText("Segurança   |");
        menuSegurança.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuSegFazerBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuSegFazerBackup.setText("Fazer Backup");
        menuSegurança.add(menuSegFazerBackup);

        menuSegRestaurarBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuSegRestaurarBackup.setText("Restaurar Backup");
        menuSegurança.add(menuSegRestaurarBackup);

        jMenuBar1.add(menuSegurança);

        menuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas_resized.png"))); // NOI18N
        menuFerramentas.setText("Ferramentas   |");
        menuFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        jMenu8.setText("Tela de Fundo");

        menuFerTelaFundoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFerTelaFundoAdicionar.setText("Adicionar Imagem");
        jMenu8.add(menuFerTelaFundoAdicionar);

        menuFerTelaFundoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFerTelaFundoRemover.setText("Remover Imagem");
        jMenu8.add(menuFerTelaFundoRemover);

        menuFerTelaFundoRestaurarPadrao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFerTelaFundoRestaurarPadrao.setText("Restaurar Padrão");
        jMenu8.add(menuFerTelaFundoRestaurarPadrao);

        menuFerramentas.add(jMenu8);

        menuFerSobreSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opção.png"))); // NOI18N
        menuFerSobreSistema.setText("Sobre o Sistema");
        menuFerramentas.add(menuFerSobreSistema);

        jMenuBar1.add(menuFerramentas);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair_resized.png"))); // NOI18N
        menuSair.setText("Sair   ");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 810, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospedesActionPerformed

    private void menuCadQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadQuartosActionPerformed

    private void menuRelResQuartosDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelResQuartosDisponiveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelResQuartosDisponiveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncionarios;
    private javax.swing.JMenuItem menuCadHospedes;
    private javax.swing.JMenuItem menuCadQuartos;
    private javax.swing.JMenuItem menuCadReserva;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuConFornecedores;
    private javax.swing.JMenuItem menuConFuncionarios;
    private javax.swing.JMenuItem menuConHospedes;
    private javax.swing.JMenuItem menuConQuartos;
    private javax.swing.JMenuItem menuConReserva;
    private javax.swing.JMenu menuConsumo;
    private javax.swing.JMenuItem menuConsumoCadProd;
    private javax.swing.JMenuItem menuConsumoConCliente;
    private javax.swing.JMenuItem menuConsumoServiços;
    private javax.swing.JMenuItem menuFerSobreSistema;
    private javax.swing.JMenuItem menuFerTelaFundoAdicionar;
    private javax.swing.JMenuItem menuFerTelaFundoRemover;
    private javax.swing.JMenuItem menuFerTelaFundoRestaurarPadrao;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenuItem menuFinConPagCad;
    private javax.swing.JMenuItem menuFinConPagCon;
    private javax.swing.JMenuItem menuFinConRecCad;
    private javax.swing.JMenuItem menuFinConRecCon;
    private javax.swing.JMenuItem menuFinalizarReserva;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenuItem menuFinanceiroBalanço;
    private javax.swing.JMenuItem menuRelFinBalanço;
    private javax.swing.JMenuItem menuRelFinContasPagar;
    private javax.swing.JMenuItem menuRelFinContasReceber;
    private javax.swing.JMenuItem menuRelFornecedores;
    private javax.swing.JMenuItem menuRelFuncionarios;
    private javax.swing.JMenuItem menuRelHospedes;
    private javax.swing.JMenuItem menuRelResQuartosDisponiveis;
    private javax.swing.JMenuItem menuRelResQuartosOcupados;
    private javax.swing.JMenuItem menuRelResReservasFuturas;
    private javax.swing.JMenu menuRelatórios;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSegFazerBackup;
    private javax.swing.JMenuItem menuSegRestaurarBackup;
    private javax.swing.JMenu menuSegurança;
    // End of variables declaration//GEN-END:variables
}
